"""Add damage_cost_reference table with seed data

Revision ID: cba0a26afce8
Revises: 6565714be4bf
Create Date: 2025-11-22 10:42:42.166395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba0a26afce8'
down_revision: Union[str, None] = '6565714be4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_cost_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(), nullable=False),
    sa.Column('damage_severity', sa.String(), nullable=False),
    sa.Column('base_cost', sa.Integer(), nullable=False),
    sa.Column('labor_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_damage_cost_reference_id'), 'damage_cost_reference', ['id'], unique=False)
    # ### end Alembic commands ###
    
    # Insert seed data
    op.execute("""
        INSERT INTO damage_cost_reference (damage_type, damage_severity, base_cost, labor_hours, notes)
        VALUES
            ('scratches', 'minor', 80, 0.5, NULL),
            ('scratches', 'major', 250, 2.0, NULL),
            ('dents', 'minor', 150, 1.0, NULL),
            ('dents', 'major', 600, 3.0, NULL),
            ('structural_damage', 'minor', 900, 5.0, NULL),
            ('structural_damage', 'major', 2500, 12.0, NULL)
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_damage_cost_reference_id'), table_name='damage_cost_reference')
    op.drop_table('damage_cost_reference')
    # ### end Alembic commands ###

